#
server:
  port: 8888
  tomcat:
    accesslog:
      encoding: utf-8

spring:
  datasource:
    username: root
    password: password
    url: jdbc:mysql://localhost:3306/drill?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&serverTimezone=GMT%2b8
    type: com.alibaba.druid.pool.DruidDataSource
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 1000MB

mybatis:
  mapper-locations: classpath:mapper/*.xml



datas:
  MD:
    std: 862.88
    mean: 1892.28
  WOB:
    std: 3.53
    mean: 5.39
  SP:
    std: 4564.3
    mean: 16750.58
  TQ:
    std: 4.78
    mean: 10.82
  RS:
    std: 35.55
    mean: 136.51
  MF:
    std: 1038.33
    mean: 3267.38
  HL:
    std: 17.74
    mean: 123.59
  TVD:
    std: 791.45
    mean: 1810.23
  ROP:
    std: 15.52
    mean: 26.22


#  type-aliases-package: com.srx.spring.development.Entities

#logging:
#  file:
#    name: ./log/development/error.log
